In [1]:
import numpy as np                                           #(deals with array operations since python only consists lists no arrays, math module cannot perform array operations)
import pandas as pd                                          #(works with dataframes)
import matplotlib.pyplot as plt                              #(for data visualization bars,graphs, plots, histograms)
import seaborn as sb                                         #(data visualization, statistical analysis)
%matplotlib inline
#(creates within the window for plots,graphs,bars)

In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/Content/survey_lung_cancer.csv')
print('data imported')

data imported


In [4]:
dataset.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [5]:
dataset.tail()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
304         2                    2                      2           1   
305         2                    2                      1           2   
306         2                    1                      1           2   
307         2                    2                      1           2   
308         1                    1                      2           1   

    LUNG_CANCER  
304         YES  
305         YES  
306         YES  
307         YES  
308         YES

In [6]:
dataset.describe(include = 'all')

GENDER         AGE     SMOKING  YELLOW_FINGERS     ANXIETY  \
count     309  309.000000  309.000000      309.000000  309.000000   
unique      2         NaN         NaN             NaN         NaN   
top         M         NaN         NaN             NaN         NaN   
freq      162         NaN         NaN             NaN         NaN   
mean      NaN   62.673139    1.563107        1.569579    1.498382   
std       NaN    8.210301    0.496806        0.495938    0.500808   
min       NaN   21.000000    1.000000        1.000000    1.000000   
25%       NaN   57.000000    1.000000        1.000000    1.000000   
50%       NaN   62.000000    2.000000        2.000000    1.000000   
75%       NaN   69.000000    2.000000        2.000000    2.000000   
max       NaN   87.000000    2.000000        2.000000    2.000000   

        PEER_PRESSURE  CHRONIC DISEASE    FATIGUE     ALLERGY     WHEEZING  \
count      309.000000       309.000000  309.000000  309.000000  309.000000   
unique            NaN              NaN         NaN         NaN         NaN   
top               NaN              NaN         NaN         NaN         NaN   
freq              NaN              NaN         NaN         NaN         NaN   
mean         1.501618         1.504854    1.673139    1.556634    1.556634   
std          0.500808         0.500787    0.469827    0.497588    0.497588   
min          1.000000         1.000000    1.000000    1.000000    1.000000   
25%          1.000000         1.000000    1.000000    1.000000    1.000000   
50%          2.000000         2.000000    2.000000    2.000000    2.000000   
75%          2.000000         2.000000    2.000000    2.000000    2.000000   
max          2.000000         2.000000    2.000000    2.000000    2.000000   

        ALCOHOL CONSUMING    COUGHING  SHORTNESS OF BREATH  \
count          309.000000  309.000000           309.000000   
unique                NaN         NaN                  NaN   
top                   NaN         NaN                  NaN   
freq                  NaN         NaN                  NaN   
mean             1.556634    1.579288             1.640777   
std              0.497588    0.494474             0.480551   
min              1.000000    1.000000             1.000000   
25%              1.000000    1.000000             1.000000   
50%              2.000000    2.000000             2.000000   
75%              2.000000    2.000000             2.000000   
max              2.000000    2.000000             2.000000   

        SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
count              309.000000  309.000000         309  
unique                    NaN         NaN           2  
top                       NaN         NaN         YES  
freq                      NaN         NaN         270  
mean                 1.469256    1.556634         NaN  
std                  0.499863    0.497588         NaN  
min                  1.000000    1.000000         NaN  
25%                  1.000000    1.000000         NaN  
50%                  1.000000    2.000000         NaN  
75%                  2.000000    2.000000         NaN  
max                  2.000000    2.000000         NaN

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64 
 2   SMOKING                309 non-null    int64 
 3   YELLOW_FINGERS         309 non-null    int64 
 4   ANXIETY                309 non-null    int64 
 5   PEER_PRESSURE          309 non-null    int64 
 6   CHRONIC DISEASE        309 non-null    int64 
 7   FATIGUE                309 non-null    int64 
 8   ALLERGY                309 non-null    int64 
 9   WHEEZING               309 non-null    int64 
 10  ALCOHOL CONSUMING      309 non-null    int64 
 11  COUGHING               309 non-null    int64 
 12  SHORTNESS OF BREATH    309 non-null    int64 
 13  SWALLOWING DIFFICULTY  309 non-null    int64 
 14  CHEST PAIN             309 non-null    int64 
 15  LUNG_CANCER            

In [ ]:
dataset = dataset.drop(columns = ['YELLOW_FINGERS','PEER_PRESSURE','CHRONIC DISEASE','ALCOHOL CONSUMING'])

In [8]:
dataset.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [9]:
dataset = pd.get_dummies(dataset)

In [10]:
dataset.head()

AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  \
0   69        1               2        2              1                1   
1   74        2               1        1              1                2   
2   59        1               1        1              2                1   
3   63        2               2        2              1                1   
4   63        1               2        1              1                1   

   FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0         2         1         2                  2         2   
1         2         2         1                  1         1   
2         2         1         2                  1         2   
3         1         1         1                  2         1   
4         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  GENDER_F  GENDER_M  \
0                    2                      2           2         0         1   
1                    2                      2           2         0         1   
2                    2                      1           2         1         0   
3                    1                      2           2         0         1   
4                    2                      1           1         1         0   

   LUNG_CANCER_NO  LUNG_CANCER_YES  
0               0                1  
1               0                1  
2               1                0  
3               1                0  
4               1                0

In [11]:
dataset = dataset.drop(columns = ['GENDER_M','LUNG_CANCER_NO'])

In [12]:
dataset.head()

AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  \
0   69        1               2        2              1                1   
1   74        2               1        1              1                2   
2   59        1               1        1              2                1   
3   63        2               2        2              1                1   
4   63        1               2        1              1                1   

   FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0         2         1         2                  2         2   
1         2         2         1                  1         1   
2         2         1         2                  1         2   
3         1         1         1                  2         1   
4         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  GENDER_F  \
0                    2                      2           2         0   
1                    2                      2           2         0   
2                    2                      1           2         1   
3                    1                      2           2         0   
4                    2                      1           1         1   

   LUNG_CANCER_YES  
0                1  
1                1  
2                0  
3                0  
4                0

In [13]:
target = dataset['LUNG_CANCER_YES']
predictor = dataset.drop(columns = ['LUNG_CANCER_YES'])

In [14]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
predictor = ss.fit_transform(predictor)

In [15]:
predictor[5]

array([ 1.50382491, -1.13529242,  0.86929961, -0.99676897, -1.0032415 ,
        0.99033794,  0.6968335 ,  0.892475  ,  0.892475  , -1.12047956,
        0.85220712,  0.74873631, -0.94029056, -1.12047956,  1.04978132])

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(predictor, target, test_size = 0.2, random_state = 0)

In [17]:
# degree of randomization - random_state = 0

In [18]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train, y_train)
lr_predicted = lr.predict(x_test)

In [19]:
from sklearn.metrics import accuracy_score
print(accuracy_score(lr_predicted, y_test))

0.9032258064516129


In [20]:
# SVM kernel = 'rbf
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

In [21]:
y_pred = classifier.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 4  6]
 [ 1 51]]


0.8870967741935484

In [23]:
# SVM kernel = 'linear'
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [24]:
y_pred = classifier.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 6  4]
 [ 2 50]]


0.9032258064516129

In [26]:
#NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)


GaussianNB()

In [27]:
y_pred = classifier.predict(x_test)

In [28]:
y_pred

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [29]:
y_test

63     1
231    1
167    1
159    0
189    1
      ..
34     0
250    1
33     1
21     1
103    1
Name: LUNG_CANCER_YES, Length: 62, dtype: uint8

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [31]:
cm

array([[ 5,  5],
       [ 3, 49]])

In [32]:
ac

0.8709677419354839

In [33]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [34]:
x_train, x_test, y_train, y_test = train_test_split(predictor, target, test_size = 0.2, random_state = 0)

In [35]:
knn_model = KNeighborsClassifier(n_neighbors= 5)
knn_model.fit(x_train, y_train)
y_pred = knn_model.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.8709677419354839


In [36]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='gini')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.8870967741935484


In [37]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.8387096774193549


In [38]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(criterion='gini')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.9032258064516129


In [39]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(criterion='entropy')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.9032258064516129


In [41]:
from time import time
parameters = {'penalty' : ['l1', 'l2', 'elasticnet', None],
              'solver' : ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
              'max_iter' : [100, 200, 300, 400, 500],
              }
#we are checking in the different variation of numerical values
#in the parameters of random forest classifier

from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator = lr, # Make sure classifier points to the RF model
                           param_grid = parameters,
                           scoring = "accuracy",
                           cv = 10,#from k-fold validation
                           n_jobs = -1)#to use the entire core of the machine

t0 = time()#just to check how much time it takes to excute the program
grid_search = grid_search.fit(x_train, y_train)
t1 = time()
print("Took %0.2f seconds" % (t1 - t0))

rf_best_accuracy = grid_search.best_score_
rf_best_parameters = grid_search.best_params_
rf_best_accuracy, rf_best_parameters

Took 5.50 seconds


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
550 fits failed out of a total of 1200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: So

(0.9311666666666667, {'max_iter': 100, 'penalty': 'l2', 'solver': 'liblinear'})